### ISSUE TITLE
H2HConstants cannot be changed

### ISSUE THREAD

**Issue by amclees** [xv435/PERSYST#2]
Our requirements state that configurations must be modifiable. Since H2HConstants uses static final variables with hardcoded values, we cannot use reflection to modify them at runtime.

We can either:

<ol>
<li>Only implement non-H2HConstants configurations</li>
<li>Use the H2H source code instead of the binaries</li>
</ol>

If anyone has any better ideas, they would be appreciated.

**Comment by synergy1095** [comment]
H2Hconstants is meant to be used as default values not as a modified configuration object, that's what the configuration stuff is for

**Comment by synergy1095** [comment]
Procedure is load default to config templates and then modify

**Comment by amclees** [comment]
Some areas of H2H grab straight from H2H constants, like encryption key size and file chunk size. It seems this will only apply to certain parts of the constants though. I searched for direct references and it seems that most of them are not particularly relevant to be changed by the user, so I am closing this issue.
